---
title: "Simulado 01"
output:
  word_document:
    reference_docx: estilo.docx
params:
  ranking: NA
  gabarito: NA
  # pdf_document:
  #   includes:
  #     in_header: header.tex
  #   keep_tex: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#knitr::opts_knit$set(base.dir = normalizePath(tempdir(), winslash = '/'))
library(tidyverse)
library(flextable)
library(ggthemes)

```

```{r tabelas, include=FALSE}
# ranking_int= params$ranking
ranking= params$ranking
compar= ranking %>% gather(Categorias,Pontos,-c(Nome,Area))
gabarito= params$gabarito %>% data.frame()
marca= gabarito[,c(2,3,5)]
colnames(marca)= c("ITEM","ALUNO","GABARITO")
marca=marca%>%select(GABARITO,ALUNO)
tmarca = t(marca)%>% as.data.frame() %>% rownames_to_column()
colnames(tmarca)=c("ITEM",1:100)
# marca_t=list()
# for(k in 1:5){
#   if(k==1){
#     marca_t[k]= marca[,1:(20*k+1)]
#   }else{
#     marca_t[k]= marca[,c(1,(20*(k-1)+2:(20*k+1)))]
#   }
# 
# }


```


## `r toupper(unique(ranking$Nome))`

<br/>

### GABARITO DO(A) ALUNO(A)

<br/>

```{r marcacao1, echo=FALSE}
tmarca[,1:21]%>% flextable() %>% align_text_col(align = "center") %>%
   bold(j=1, bold=TRUE) %>% fontsize(size=7, part="all") %>%
   theme_zebra() %>% autofit()

```
<br/>

```{r marcacao2, echo=FALSE}
tmarca[,c(1,22:41)]%>% flextable() %>% align_text_col(align = "center") %>%
   bold(j=1, bold=TRUE) %>% fontsize(size=7, part="all") %>%
   theme_zebra() %>% autofit()

```
<br/>

```{r marcacao3, echo=FALSE}
tmarca[,c(1,42:61)]%>% flextable() %>% align_text_col(align = "center") %>%
   bold(j=1, bold=TRUE) %>% fontsize(size=7, part="all") %>%
   theme_zebra() %>% autofit()
```
<br/>

```{r marcacao4, echo=FALSE}
tmarca[,c(1,62:81)]%>% flextable() %>% align_text_col(align = "center") %>%
   bold(j=1, bold=TRUE) %>% fontsize(size=7, part="all") %>%
   theme_zebra() %>% autofit()

```
<br/>

```{r marcacao5, echo=FALSE}
tmarca[,c(1,82:101)]%>% flextable() %>% align_text_col(align = "center") %>%
   bold(j=1, bold=TRUE) %>% fontsize(size=7, part="all") %>%
   theme_zebra() %>% autofit()

```
<br/>
<br/>
<br/>

### DESEMPENHO INDIVIDUAL

```{r desemp_ind, echo=FALSE}
ranking %>% select(2:6) %>% flextable() %>%  theme_box() %>% colformat_int(c("Acertos","Erros")) %>%
set_header_labels(c("Área do Conhecimento","Acertos","Erros","% de Acerto","Classificação")) %>% align(align = "center", part="all") %>% autofit() 

```


### DESEMPENHO DO GRUPO
```{r desemp_grupo, echo=FALSE}
ranking %>% select(2,7:10) %>% flextable() %>% 
  theme_box() %>% 
  colformat_int(c("Maximo","Minimo"))%>% 
  align(align = "center", part="all") %>%
  set_header_labels(c("Área do Conhecimento","Mínimo","Média","Máximo","Desvio Padrão"))%>% 
  autofit() 

```
\pagebreak

### COMPARATIVO

```{r comparativo, echo=FALSE, fig.width=8, fig.height=10}
# compar %>% filter(Categorias %in% c("Acertos","Media")) %>% flextable() %>% autofit()

 compar %>% filter(Categorias %in% c("Acertos","Media")) %>% ggplot(aes(Categorias,Pontos))+geom_col(fill="blue")+geom_text(aes(label=Pontos),nudge_y =1)+
  theme_few()+ theme(plot.title = element_text(hjust = 0.5), axis.ticks = element_blank(), axis.text.y=element_blank())+facet_wrap(~Area, ncol=2, scales = "free_y")+
   labs(x="",y="")

#compar$`Área do Conhecimento`
```

